package facebook

var (
	PAGE_NAMES = map[string]string{
		"Travis AFB, California":               "travispassengerterminal",
		"Baltimore-Washington IAP, Maryland":   "BWIPassengerTerminal",
		"Dover AFB, Delaware":                  "DoverPaxTerminal",
		"Fairchild AFB, Washington":            "FairchildPaxTerminal",
		"Jacksonville NAS, Florida":            "Jacksonvillepassengerterminal",
		"JB Andrews, Maryland":                 "204595186255795",
		"JB Charleston, South Carolina":        "JBCharlestonPassengerTerminal",
		"JB Lewis-McChord, Washington":         "mcchordpt",
		"JB McGuire-Dix-Lakehurst, New Jersey": "JBMDLPaxTerm",
		"Little Rock AFB, Arkansas":            "173212306112777",
		"MacDill AFB, Florida":                 "MacDillPassengerTerminal",
		"McConnell AFB, Kansas":                "McConnellPassengerTerminal",
		"NS Norfolk, Virginia":                 "NorfolkPassengerTerminal",
		"Pope Field, North Carolina":           "popepassengerterminal",
		"Scott AFB, Illinois":                  "302813853094915",
		"Seattle-Tacoma IAP, Washington":       "SeaTacAmcPassengerTerminal",
		"Andersen AB, Guam":                    "AndersenPassengerTerminal",
		"Aviano AB, Italy":                     "340217489359669",
		"Incirlik AB, Turkey":                  "728AMSTROP",
		"JB Elmendorf-Richardson, Alaska":      "204965679537720",
		"JB Pearl Harbor-Hickam, Hawaii":       "HickamAMC",
		"Kadena AB, Okinawa, Japan":            "AMCKadena",
		"Lajes AB, Azores Portugal":            "365136066860819",
		//"MCAS Iwakuni, Japan":                    "IwakuniPassengerTerminal",
		"Misawa AB, Japan":                       "MisawaPassengerTerminal",
		"NAS Sigonella, Italy":                   "332837856791726",
		"NS Guantanamo Bay, Cuba":                "297798750277960",
		"NS Rota, Spain":                         "NavalStationRotaSpainPassengerTerminal",
		"NSA Bahrain, Bahrain":                   "BahrainPassengerTerminal",
		"NSA Naples, Italy":                      "228247760626570",
		"NSA Souda Bay, Crete Greece":            "soudabaypassengerterminal1",
		"NSF Diego Garcia, British Indian Ocean": "242934902443795",
		"Osan AB, Rep of Korea":                  "OsanPassengerTerminal",
		"RAAF Base Richmond, Australia":          "RichmondAMC",
		"RAF Mildenhall, United Kingdom":         "RAFMildenhallPassengerTerminal",
		"Ramstein AB, Germany":                   "139447339417453",
		"Spangdahlem AB, Germany":                "SpangdahlemPassengerTerminal",
		"Yokota AB, Japan":                       "YokotaPassengerTerminal",
	}
)
